### ISSUE TITLE
Permitir a cada grupo personalizar el repositorio en el que abrir issues

### ISSUE THREAD

**Issue by ivanhercaz** [makersGC/rdaneelolivaw#27]
Ahora mismo se podría decir que R. Daneel solo es capaz de añadir issues a un mismo repositorio desde diferentes grupos. Esto se debe a que el repositorio en el que Daneel trabaja se configura a partir de la variable de entorno `DANEEL_GITHUB_REPO_ISSUES`. Para solucionar esto, se podría aplicar alguno de los métodos o partes de varias de las propuestas que expongo abajo.

### Propuesta 1.

  1. Administrador añade a R. Daneel a un grupo.
  2. Daneel saluda, explica su funcionamiento y pide que se le configure. Solicita:
    - El repositorio en el que publicar proponer issues (¿más generales?).
    - El repositorio para recopilar recursos (¿más específico del tipo `awesome-micropython`).
  3. Si se ha configurado correctamente, al ejecutar `/proponer` o `/issue`, se publicarán en el repositorio establecido al configurar R. Daneel; si no se estableció uno, R. Daneel comunicará que no hay un repositorio configurado y que esa tarea debe ser realizada por un administrador.

En este caso habría un fichero de configuración YAML con la siguiente estructura:

```yaml
nombre_grupo_telegram:
  id_grupo: id_del_grupo_de_telegram
  repositorio_general: org/repo_general
  repositorio_lista: org/repo_lista
```

### Propuesta 2.

  1. Administrador añade a R. Daneel.
  2. Daneel saluda, explica su funcionamiento y pide que se le configure. Solicita:
    - Saber si el grupo desea publicar issues en un repositorio
    - En caso afirmativo:
       - Pregunta por el repositorio (con formato `organización/repositorio` o `usuario/repositorio`).
       - Pregunta por otro repositorio, hasta que se le diga que ya están todos.
    - En caso negativo pasa al siguiente paso de la configuración.
  3. Al ejecutar el comando `/proponer` o `/issue` R. Daneel preguntaría en qué repositorio se quiere publicar la issue.

En este caso habría un fichero de configuración YAML con la siguiente estructura:

```yaml
nombre_grupo_telegram:
  id_grupo: id_del_grupo_de_telegram
  repositorios:
    org/repo_general
    org/repo_lista
    org/repo_bot
```

### Propuesta... ¡extra!

¿Y si se asocia a cada repositorio un hashtag que si es utilizado ejecuta el comando automáticamente? Por ejemplo, para la propuesta uno el archivo de configuración quedaría como el siguiente:

```yaml
nombre_grupo_telegram:
  id_grupo: id_del_grupo_de_telegram
  repositorio_general:
    repo: org/repo_general
    hashtag: general
  repositorio_lista:
    repo: org/repo_lista
    hashtag: lista
```

Mientras que para la propuesta 2 la configuración sería similar a:

```yaml
nombre_grupo_telegram:
  id_grupo: id_del_grupo_de_telegram
  repositorios:
    repo_01:
       repo: org/repo_general
       hashtag: general
    repo_02: 
       repo: org/repo_lista
       hashtag: lista
    repo_03:
       repo: org/repo_bot
       hashtag: bot
```

Si se aplica la propuesta 2, cuando el usuario ejecute `/issue` R. Daneel le preguntará en que repositorio quiere publicarlo; pero si el usuario utiliza el hashtag asociado a un repositorio, por ejemplo, `recurso [propuesto](url_recurso) #lista`, ese mensaje se publicará en el repositorio al que está asociado ese hashtag.

----

Estoy seguro de que esta propuesta se puede pulir mucho más, pero creo que al menos es un paso para lograr que R. Daneel sea fácil de introducir en otros grupos sin necesidad de estar toqueteando las variables de entorno ni de desplegar varias instancias del mismo.
